---

- name: Configuring port/protocol/network rules
  ufw:
    delete: "{{ item.delete | default(omit) }}"
    direction: "{{ item.direction | default(omit) }}"
    from_ip: "{{ item.from_ip | default(omit) }}"
    from_port: "{{ item.from_port | default(omit) }}"
    insert: "{{ item.insert | default(omit) }}"
    interface: "{{ item.interface | default(omit) }}"
    log: "{{ item.log | default(omit) }}"
    logging: "{{ item.logging | default(omit) }}"
    name: "{{ item.name | default(omit) }}"
    policy: "{{ item.policy | default(omit) }}"
    port: "{{ item.port | default(omit) }}"
    proto: "{{ item.proto | default(omit) }}"
    rule: "{{ item.rule | default('allow') }}"
    state: "{{ item.state | default(omit) }}"
    to_ip: "{{ item.to_ip | default(omit) }}"
    to_port: "{{ item.to_port | default(omit) }}"
  with_items: "{{ ufw_rules }}"

- name: Configuring group port/protocol/network rules
  ufw:
    delete: "{{ item.0.delete | default(omit) }}"
    direction: "{{ item.0.direction | default(omit) }}"
    from_ip: "{{ item.1 | default(omit) }}"
    from_port: "{{ item.0.from_port | default(omit) }}"
    insert: "{{ item.0.insert | default(omit) }}"
    interface: "{{ item.0.interface | default(omit) }}"
    log: "{{ item.0.log | default(omit) }}"
    logging: "{{ item.0.logging | default(omit) }}"
    name: "{{ item.0.name | default(omit) }}"
    policy: "{{ item.0.policy | default(omit) }}"
    port: "{{ item.0.port | default(omit) }}"
    proto: "{{ item.0.proto | default(omit) }}"
    rule: "{{ item.0.rule | default('allow') }}"
    state: "{{ item.0.state | default(omit) }}"
    to_ip: "{{ item.0.to_ip | default(omit) }}"
    to_port: "{{ item.0.to_port | default(omit) }}"
  with_subelements:
    - "{{ ufw_group_rules }}"
    - from_ips

- name: Configuring application rules
  ufw:
    name: "{{ item.name }}"
    rule: "{{ item.rule if item.rule is defined else 'allow' }}"
  with_items: "{{ ufw_applications }}"

- name: Configuring firewall
  template:
    src: etc-default-ufw.j2
    dest: /etc/default/ufw
    owner: root
    group: root
    mode: 0644
  notify: reload ufw
